package com.atlasproject2.dynamoproject.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;


@Data
@DynamoDBTable(tableName = "Person")
public class Person {
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstName;
    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    private int age;

    public int incrementAge(){
        this.age++;
        return this.age;
    }

}
